"""empty message

Revision ID: 101f57eb78d0
Revises: d9872a6ccf32
Create Date: 2025-02-25 03:07:34.238788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101f57eb78d0'
down_revision = 'd9872a6ccf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=True))
        batch_op.drop_column('emai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emai', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
